#!/bin/bash

print("selected EC2 attr & value")
print("=====")

response=pricing.describe_services(ServiceCode='AmazonEC2')
attrs=response['Services'][0]['AttributeNames']

for attr in attrs:
	respone=pricing.get_attribute_values(ServiceCode='AmazonEC2', AttributeName=attr)

	values=[]
	for attr_value in response['AttributeValues']:
		values.append(attr_value['Value'])
	print(" " + attr + ": " + ", " .join(values))

